spring:
  application:
    name: x6-user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/x6_user
    username: test
    password: ${DB_PG_PWD}
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
server:
  port: ${APP_PORT:8081}